services:
  patlytics-inf-app:
    image: stevelu1116/patlytics-inf-app:main
    container_name: patlytics-inf-app
    ports:
      - "5373:5373"
    networks:
      - docker_default
networks:
  docker_default:
    driver: bridge
    external: true
    name: patlytics-inf-network